---
kind: pipeline
name: latest-amd64
type: docker
platform:
  arch: amd64
  os: linux
steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: p3000/bibler-server
      tags: [latest-linux-amd64]
      # auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
name: latest-arm64
type: docker
platform:
  arch: arm64
  os: linux
steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: p3000/bibler-server
      tags: [latest-linux-arm64]
      # auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
name: manifest
kind: pipeline
type: docker
depends_on:
  - latest-amd64
  - latest-arm64
steps:
  - name: publish-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: p3000/bibler-server:latest
      template: p3000/bibler-server:latest-OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
trigger:
  status:
    - success
